%%{init: {'theme': 'default', 'scale': 2}}%%
graph TD
  A[<img src="https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/fxemoji--notebook.png?raw=true" width="100"/> <br/> React] --> B[Process]
  B --> C[Done]
