%%{init: {'theme': 'default', 'scale': 2}}%%
graph TD

  PulsedLaserDeposition --> Notebook
  PulsedLaserDeposition --> RHEED
  PulsedLaserDeposition --> XRD
  PulsedLaserDeposition --> AtomicForceMicroscopy
  PulsedLaserDeposition --> ElectronMicroscopy

  PLD@{ img: "https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/PLD-Chamber.png?raw=true", h: 200, w: 200, pos: "b"}
  Notebook@{ img: "https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/notebook.png?raw=true", h: 200, w: 200, pos: "b"}
  RHEED@{ img: "https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/rheed.svg?raw=true", h: 200, w: 200, pos: "b"}
  XRD@{ img: "https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/XRD-icon.png?raw=true", h: 200, w: 200, pos: "b"}
  AtomicForceMicroscopy@{ img: "https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/Cypher-2.png?raw=true", h: 200, w: 200, pos: "b"}
  ElectronMicroscopy@{ img: "https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/Electron_microscope-01.svg?raw=true", h: 200, w: 200, pos: "b"}

  n1["This is sample label"] --> n2["Untitled Node"]

  %% docker run --rm -u `id -u`:`id -g` -v /Users/joshuaagar/SSMC-CI-Madison-5-20-2025/slides/pld-dataflow:/data minlag/mermaid-cli -i pld-dataflow.mmd -o pld-dataflow.svg