%%{init: {'theme': 'default', 'scale': 2}}%%
graph TD
  PulsedLaserDeposition[Pulsed Laser Deposition]
  Notebook[Notebook]
  RHEED[RHEED]
  XRD[XRD]
  AtomicForceMicroscopy[Atomic Force Microscopy]
  ElectronMicroscopy[Electron Microscopy]

  A[<img src="https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/icon/fxemoji--notebook.png?raw=true" width="100"/> <br/> React] --> B[Process]
  D[<img src="https://github.com/jagar2/SSMC-CI-Madison-5-20-2025/blob/main/public/pld-schematic/PLD-Schematic-All.svg?raw=true" width="100"/> <br/> React] --> B[Process]
